config/routes.rb
Jets.application.routes.draw do
  resources :runners
  get "runners/:id/job_request", to: "runners#job_request", as: 'job_request_runner'
  root "runners#index"

  # The jets/public#show controller can serve static utf8 content out of the public folder.
  # Note, as part of the deploy process Jets uploads files in the public folder to s3
  # and serves them out of s3 directly. S3 is well suited to serve static assets.
  # More info here: https://rubyonjets.com/docs/extras/assets-serving/
  any "*catchall", to: "jets/public#show"
end

app/models/application_item.rb
class ApplicationItem < Dynomite::Item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :runner

  after_commit :execute_async, on: :create

  def trace_path
    File.join(trace_dir, "#{id}.log").tap do |path|
      FileUtils.touch(path)
    end
  end

  private

  def trace_dir
    # Only /tmp seems to be writable in AWS Lambda.
    File.join('/tmp', 'traces').tap do |path|
      FileUtils.mkdir_p(path)
    end
  end

  def execute_async
    RunnerJob.perform_later(:execute_job, { job_id: self.id })
  end
end

app/models/jobs/script.rb
module Jobs
  class Script
    attr_reader :job

    FINISH_LOG = %Q{Job Finished!}.freeze

    FUNCTIONS = <<-EOS
function finalize {
  echo "#{FINISH_LOG}"
}
EOS

    TRAPS = <<-EOS
trap finalize EXIT
EOS

    def self.generate!(job)
      @job = job

      Dir.mktmpdir do |dir|
        script_path = File.join(dir, 'tmp-script')

        File.open(script_path, 'w') do |stream|
          stream.write("#!/bin/bash\n")
          stream.write("set -e\n")
          stream.write("#{FUNCTIONS}\n")
          stream.write("#{TRAPS}\n")
          stream.write("exec > #{job.trace_path} 2>&1\n")

          stream.write(%Q{echo "GitLab Serverless Runner Version: 0.1.0"\n})

          job.spec['variables'].each do |variable|
            stream.write(%Q{export #{variable['key']}="#{variable['value']}"\n})
          end

          job.spec['steps'].first['script'].each do |script|
            stream.write("#{script}\n")
          end
        end

        FileUtils.chmod("+x", script_path)

        yield script_path
      end
    end
  end
end

app/models/runner.rb
class Runner < ApplicationRecord
  has_many :jobs

  validates :url, presence: true
  validates :token, presence: true
  validates :concurrency, inclusion: { in: 1..10 }

  enum runtime: {
    ruby_2_5: 0
  }

  scope :has_capacity,
    -> { where('concurrency > (SELECT COUNT(*) FROM jobs WHERE runners.id = jobs.runner_id)') }

  def has_capacity?
    jobs.count < concurrency
  end

  def capacity
    concurrency - jobs.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < Jets::Controller::Base
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show, :edit, :update, :delete, :job_request]

  # GET /runners
  def index
    @runners = Runner.all
  end

  # GET /runners/1
  def show
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  def job_request
    RunnerJob.perform_now(:request_jobs)

    render :index
  end

  # POST /runners
  def create
    @runner = Runners::RegisterRunnerService.new(runner_params).execute

    if @runner.persisted?
      if request.xhr?
        render json: {success: true, location: url_for(@runner)}
      else
        redirect_to runner_path(@runner)
      end
    else
      render :new
    end
  end

  # PUT /runners/1
  def update
    if CreateRunnerService.new(runner_params).execute(@runner)
      if request.xhr?
        render json: {success: true, location: url_for(@runner)}
      else
        redirect_to runner_path(@runner)
      end
    else
      render :edit
    end
  end

  # DELETE /runners/1
  def delete
    @runner.destroy
    if request.xhr?
      render json: {success: true}
    else
      redirect_to runners_path
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_runner
    @runner = Runner.find(params[:id])
  end

  def runner_params
    params.require(:runner).permit(:url, :token, :description, :tags, :runtime, :concurrency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "#000000", :name => "theme-color"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    = csrf_meta_tags
    %title Jets App
    = javascript_pack_tag "application"
    = stylesheet_pack_tag "theme"
    %link{:href => favicon_path, :rel => "shortcut icon"}/
  %body
    %section.starter
      .container
        .row
          .col-md-9.content-body
            - if @title
              %h1= @title
            = yield

app/views/runners/_form.haml
= form_with(model: runner, local: true) do |form|
  - if runner.errors.any?
    #error_explanation
      %h2
        = pluralize(runner.errors.count, "error")
        prohibited this runner from being saved:
      %ul
        - runner.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :url
    = form.text_field :url, value: 'http://local.gitlab.test:8181/'
  .field
    = form.label :token
    = form.text_field :token
  .field
    = form.label :description
    = form.text_field :description
  .field
    = form.label :tags
    = form.text_field :tags
  .field
    = form.label :runtime
    = form.text_field :runtime, value: 'ruby_2_5'
  .field
    = form.label :concurrency
    = form.text_field :concurrency, value: runner.concurrency.to_s
  .actions
    = form.submit

app/views/runners/edit.haml
%h1 Editing Runner
= render 'form', runner: @runner
= link_to 'Show', @runner
|
= link_to 'Back', runners_path

app/views/runners/index.haml
%h1 Runners
%table
  %thead
    %tr
      %th URL
      %th Token
      %th Description
      %th Tags
      %th Runtime
      %th{:colspan => "3"}
  %tbody
    - @runners.each do |runner|
      %tr.jets-element-to-delete
        %td= runner.url
        %td= runner.token
        %td= runner.description
        %td= runner.tags
        %td= runner.runtime
        %td= link_to 'Show', runner
        %td= link_to 'Edit', edit_runner_path(runner)
        %td= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Test Request Job', job_request_runner_path(runner)
%br/
= link_to 'New Runner', new_runner_path

app/views/runners/new.haml
%h1 New Runner
= render 'runners/form', runner: @runner
= link_to 'Back', runners_path

app/views/runners/show.haml
%p
  %strong URL:
  = @runner.url
%p
  %strong Token:
  = @runner.token
%p
  %strong Description:
  = @runner.description
%p
  %strong Tags:
  = @runner.tags
%p
  %strong Runtime:
  = @runner.runtime
= link_to 'Edit', edit_runner_path(@runner)
|
= link_to 'Back', runners_path